config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]

  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index, :show]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <table class="table table-hover">
      <thead>
        <h2>お知らせ</h2>
      </thead>
      <tbody>
        <% @notifications.each do |notification| %>
          <tr>
            <td>
              <!-- <p><%= notification.read  %></p> -->
              <p><%= notificationread = notification.read == false ? '未読' : '既読' %></p>
              <p><%= notification.comment.user.try(:name) %>さんが
              あなたのブログ(<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>)にコメントしました。</p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>